version: '3'

services:
  db:
    image: mysql:8
    volumes:
      - db_easy:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: complicated
      MYSQL_DATABASE: xatule
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  app:
    build:
      context: .
    ports:
      - 3030:3030
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
    volumes:
        - .:/app
    working_dir: /app
    depends_on:
      - db

volumes:
  db_easy: {}
